name: Build and publish Docker image to Github Container Registry ghcr.io

on:
  push:
    branches-ignore:
      - master
      - version-*
    paths-ignore:
      - README.md

jobs:
  build-job:
    uses: th2-net/.github/.github/workflows/compound-java-dev.yml@main
    with:
      build-target: 'Docker'
      docker-multi-platform: true
      docker-username: ${{ github.actor }}
    secrets:
      docker-password: ${{ secrets.GITHUB_TOKEN }}
      nvd-api-key: ${{ secrets.NVD_APIKEY }}
      oss-index-user: ${{ secrets.OSSINDEX_SONATYPE_USER }}
      oss-index-token: ${{ secrets.OSSINDEX_SONATYPE_TOKEN }}
      cisa-domain: ${{ secrets.CISA_DOMAIN }}
      cisa-user: ${{ secrets.CISA_USER }}
      cisa-password: ${{ secrets.CISA_PWD }}