name: Build and publish Docker image to Github Container Registry ghcr.io

on:
  push:
    branches-ignore:
      - master
      - version-*
      - dependabot**
    paths-ignore:
      - README.md

jobs:
  build-job:
    uses: th2-net/.github/.github/workflows/compound-java-dev.yml@main
    with:
      build-target: 'Docker'
      docker-username: ${{ github.actor }}
    secrets:
      docker-password: ${{ secrets.GITHUB_TOKEN }}